# 自動トリガーじゃないので手動起動すること
# TODO: matrixにして複数モデルに対応する

name: Build and Push Docker Image

on:
    workflow_dispatch:
        inputs:
            model:
                description: "ビルドするモデル"
                required: true
                type: choice
                options:
                    - qwen3:8b
                    - qwen3:4b
                    - qwen3:1.7b
                    - qwen3:0.6b

env:
    REGISTRY: ghcr.io
    MODEL: ${{ github.event.inputs.model }}
    # IMAGE_NAME は後で設定する（:を-に置き換えるため）
    # IMAGE_NAME: ${{ github.repository }}/ollama-${{ inputs.model }}

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Prepare variables
              id: vars
              run: |
                  echo "image_name=${MODEL://:/-}" >> "$GITHUB_OUTPUT"
              env:
                  model: ${{ github.event.inputs.model }}

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ steps.vars.outputs.image_name }}
                  tags: |
                      type=raw,value=latest
                      type=sha,prefix={{branch}}-

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: ./docker/ollama-with-model
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  build-args: "MODEL=${{ inputs.model }}"
