on:
    workflow_dispatch:

jobs:
    test-ollama-action:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            # 一旦コメントアウト
            # - name: Run model
            #   id: run-model
            #   uses: ai-action/ollama-action@v1
            #   with:
            #       model: qwen3:8b
            #       prompt: |
            #           こんにちは、あなたの名前は何ですか？

            # - name: Show output
            #   run: 'echo "Model output: [$response]"'
            #   env:
            #       response: "${{ steps.run-model.outputs.response }}"

            - name: Run model
              id: run-model
              run: |
                  docker pull ${IMAGE_NAME}
                      docker run -it --rm ${IMAGE_NAME} run qwen3:0.6b "日本で一番高い山は何でしょう？" > output.txt
                      echo "---------------------結果---------------------" && cat output.txt
                      ( echo -n "output=" && cat output.txt >> "$GITHUB_OUTPUT"
              env:
                  IMAGE_NAME: ghcr.io/kounoike/too-many-backseat-gamers/ollama-qwen3-0.6b:latest
